<?php

/**
 * BaseCustomWorkingHour
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $employee_id
 * @property date $date
 * @property integer $minutes
 * @property string $comment
 * @property integer $added_by
 * @property sfGuardUser $Employee
 * @property sfGuardUser $Adder
 * 
 * @method integer           getEmployeeId()  Returns the current record's "employee_id" value
 * @method date              getDate()        Returns the current record's "date" value
 * @method integer           getMinutes()     Returns the current record's "minutes" value
 * @method string            getComment()     Returns the current record's "comment" value
 * @method integer           getAddedBy()     Returns the current record's "added_by" value
 * @method sfGuardUser       getEmployee()    Returns the current record's "Employee" value
 * @method sfGuardUser       getAdder()       Returns the current record's "Adder" value
 * @method CustomWorkingHour setEmployeeId()  Sets the current record's "employee_id" value
 * @method CustomWorkingHour setDate()        Sets the current record's "date" value
 * @method CustomWorkingHour setMinutes()     Sets the current record's "minutes" value
 * @method CustomWorkingHour setComment()     Sets the current record's "comment" value
 * @method CustomWorkingHour setAddedBy()     Sets the current record's "added_by" value
 * @method CustomWorkingHour setEmployee()    Sets the current record's "Employee" value
 * @method CustomWorkingHour setAdder()       Sets the current record's "Adder" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomWorkingHour extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('custom_working_hour');
        $this->hasColumn('employee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('minutes', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('added_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('orderBy', 'date DESC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'employee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Adder', array(
             'local' => 'added_by',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}