<?php

/**
 * BaseWorkingHourParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $param
 * @property string $description
 * @property string $value
 * @property integer $value_leavetype_id
 * @property LeaveType $LeaveType
 * 
 * @method string               getParam()              Returns the current record's "param" value
 * @method string               getDescription()        Returns the current record's "description" value
 * @method string               getValue()              Returns the current record's "value" value
 * @method integer              getValueLeavetypeId()   Returns the current record's "value_leavetype_id" value
 * @method LeaveType            getLeaveType()          Returns the current record's "LeaveType" value
 * @method WorkingHourParameter setParam()              Sets the current record's "param" value
 * @method WorkingHourParameter setDescription()        Sets the current record's "description" value
 * @method WorkingHourParameter setValue()              Sets the current record's "value" value
 * @method WorkingHourParameter setValueLeavetypeId()   Sets the current record's "value_leavetype_id" value
 * @method WorkingHourParameter setLeaveType()          Sets the current record's "LeaveType" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourParameter extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_parameter');
        $this->hasColumn('param', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('value', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('value_leavetype_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));

        $this->option('orderBy', 'description ASC');
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LeaveType', array(
             'local' => 'value_leavetype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}