<?php

/**
 * BaseHoliday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Date $date
 * @property string $name
 * 
 * @method Date    getDate() Returns the current record's "date" value
 * @method string  getName() Returns the current record's "name" value
 * @method Holiday setDate() Sets the current record's "date" value
 * @method Holiday setName() Sets the current record's "name" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHoliday extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('holiday');
        $this->hasColumn('date', 'Date', null, array(
             'type' => 'Date',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}