<?php

/**
 * BaseWorkingHourLeave
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property enum $type
 * @property date $date
 * @property string $description
 * @property enum $status
 * @property integer $status_user
 * @property integer $created_by
 * @property integer $updated_by
 * @property sfGuardUser $User
 * @property sfGuardUser $StatusUser
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Updater
 * 
 * @method integer          getUserId()      Returns the current record's "user_id" value
 * @method enum             getType()        Returns the current record's "type" value
 * @method date             getDate()        Returns the current record's "date" value
 * @method string           getDescription() Returns the current record's "description" value
 * @method enum             getStatus()      Returns the current record's "status" value
 * @method integer          getStatusUser()  Returns the current record's "status_user" value
 * @method integer          getCreatedBy()   Returns the current record's "created_by" value
 * @method integer          getUpdatedBy()   Returns the current record's "updated_by" value
 * @method sfGuardUser      getUser()        Returns the current record's "User" value
 * @method sfGuardUser      getStatusUser()  Returns the current record's "StatusUser" value
 * @method sfGuardUser      getCreator()     Returns the current record's "Creator" value
 * @method sfGuardUser      getUpdater()     Returns the current record's "Updater" value
 * @method WorkingHourLeave setUserId()      Sets the current record's "user_id" value
 * @method WorkingHourLeave setType()        Sets the current record's "type" value
 * @method WorkingHourLeave setDate()        Sets the current record's "date" value
 * @method WorkingHourLeave setDescription() Sets the current record's "description" value
 * @method WorkingHourLeave setStatus()      Sets the current record's "status" value
 * @method WorkingHourLeave setStatusUser()  Sets the current record's "status_user" value
 * @method WorkingHourLeave setCreatedBy()   Sets the current record's "created_by" value
 * @method WorkingHourLeave setUpdatedBy()   Sets the current record's "updated_by" value
 * @method WorkingHourLeave setUser()        Sets the current record's "User" value
 * @method WorkingHourLeave setStatusUser()  Sets the current record's "StatusUser" value
 * @method WorkingHourLeave setCreator()     Sets the current record's "Creator" value
 * @method WorkingHourLeave setUpdater()     Sets the current record's "Updater" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourLeave extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_leave');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'IllnessWReport',
              1 => 'IllnessWoReport',
              2 => 'PaidVacation',
              3 => 'UnpaidVacation',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Pending',
              1 => 'Approved',
              2 => 'Denied',
              3 => 'Cancelled',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('status_user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as StatusUser', array(
             'local' => 'status_user',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Updater', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}