<?php

/**
 * BaseWorkingHourQuota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $quota
 * @property sfGuardUser $Employee
 * 
 * @method integer          getUserId()   Returns the current record's "user_id" value
 * @method integer          getQuota()    Returns the current record's "quota" value
 * @method sfGuardUser      getEmployee() Returns the current record's "Employee" value
 * @method WorkingHourQuota setUserId()   Sets the current record's "user_id" value
 * @method WorkingHourQuota setQuota()    Sets the current record's "quota" value
 * @method WorkingHourQuota setEmployee() Sets the current record's "Employee" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourQuota extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_quota');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quota', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}