<?php

/**
 * BaseWorkingHourWorkTypeUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $worktype_id
 * @property integer $employee_id
 * @property WorkingHourWorkType $WorkingHourWorkType
 * @property sfGuardUser $Employee
 * 
 * @method integer                 getWorktypeId()          Returns the current record's "worktype_id" value
 * @method integer                 getEmployeeId()          Returns the current record's "employee_id" value
 * @method WorkingHourWorkType     getWorkingHourWorkType() Returns the current record's "WorkingHourWorkType" value
 * @method sfGuardUser             getEmployee()            Returns the current record's "Employee" value
 * @method WorkingHourWorkTypeUser setWorktypeId()          Sets the current record's "worktype_id" value
 * @method WorkingHourWorkTypeUser setEmployeeId()          Sets the current record's "employee_id" value
 * @method WorkingHourWorkTypeUser setWorkingHourWorkType() Sets the current record's "WorkingHourWorkType" value
 * @method WorkingHourWorkTypeUser setEmployee()            Sets the current record's "Employee" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourWorkTypeUser extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_work_type_user');
        $this->hasColumn('worktype_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('employee_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WorkingHourWorkType', array(
             'local' => 'worktype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'employee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}