<?php

/**
 * BaseLeaveRequestEmployeeLimit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $employee_id
 * @property integer $type_id
 * @property decimal $leave_Limit
 * @property integer $added_by
 * @property string $comment
 * @property sfGuardUser $Employee
 * @property LeaveType $LeaveType
 * @property sfGuardUser $Adder
 * 
 * @method integer                   getEmployeeId()  Returns the current record's "employee_id" value
 * @method integer                   getTypeId()      Returns the current record's "type_id" value
 * @method decimal                   getLeaveLimit()  Returns the current record's "leave_Limit" value
 * @method integer                   getAddedBy()     Returns the current record's "added_by" value
 * @method string                    getComment()     Returns the current record's "comment" value
 * @method sfGuardUser               getEmployee()    Returns the current record's "Employee" value
 * @method LeaveType                 getLeaveType()   Returns the current record's "LeaveType" value
 * @method sfGuardUser               getAdder()       Returns the current record's "Adder" value
 * @method LeaveRequestEmployeeLimit setEmployeeId()  Sets the current record's "employee_id" value
 * @method LeaveRequestEmployeeLimit setTypeId()      Sets the current record's "type_id" value
 * @method LeaveRequestEmployeeLimit setLeaveLimit()  Sets the current record's "leave_Limit" value
 * @method LeaveRequestEmployeeLimit setAddedBy()     Sets the current record's "added_by" value
 * @method LeaveRequestEmployeeLimit setComment()     Sets the current record's "comment" value
 * @method LeaveRequestEmployeeLimit setEmployee()    Sets the current record's "Employee" value
 * @method LeaveRequestEmployeeLimit setLeaveType()   Sets the current record's "LeaveType" value
 * @method LeaveRequestEmployeeLimit setAdder()       Sets the current record's "Adder" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveRequestEmployeeLimit extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leave_request_employee_limit');
        $this->hasColumn('employee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('leave_Limit', 'decimal', null, array(
             'type' => 'decimal',
             'scale' => 1,
             'notnull' => true,
             ));
        $this->hasColumn('added_by', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));

        $this->option('orderBy', 'created_at DESC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'employee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LeaveType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser as Adder', array(
             'local' => 'added_by',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($versionable0);
    }
}