<?php

/**
 * BaseLeaveRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $type_id
 * @property enum $status
 * @property date $start_Date
 * @property date $end_Date
 * @property integer $day_Count
 * @property string $report_Comment
 * @property date $report_Date
 * @property date $report_Received
 * @property sfGuardUser $Employee
 * @property LeaveType $LeaveType
 * @property Doctrine_Collection $WorkingHourDay
 * 
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method integer             getTypeId()          Returns the current record's "type_id" value
 * @method enum                getStatus()          Returns the current record's "status" value
 * @method date                getStartDate()       Returns the current record's "start_Date" value
 * @method date                getEndDate()         Returns the current record's "end_Date" value
 * @method integer             getDayCount()        Returns the current record's "day_Count" value
 * @method string              getReportComment()   Returns the current record's "report_Comment" value
 * @method date                getReportDate()      Returns the current record's "report_Date" value
 * @method date                getReportReceived()  Returns the current record's "report_Received" value
 * @method sfGuardUser         getEmployee()        Returns the current record's "Employee" value
 * @method LeaveType           getLeaveType()       Returns the current record's "LeaveType" value
 * @method Doctrine_Collection getWorkingHourDay()  Returns the current record's "WorkingHourDay" collection
 * @method LeaveRequest        setUserId()          Sets the current record's "user_id" value
 * @method LeaveRequest        setTypeId()          Sets the current record's "type_id" value
 * @method LeaveRequest        setStatus()          Sets the current record's "status" value
 * @method LeaveRequest        setStartDate()       Sets the current record's "start_Date" value
 * @method LeaveRequest        setEndDate()         Sets the current record's "end_Date" value
 * @method LeaveRequest        setDayCount()        Sets the current record's "day_Count" value
 * @method LeaveRequest        setReportComment()   Sets the current record's "report_Comment" value
 * @method LeaveRequest        setReportDate()      Sets the current record's "report_Date" value
 * @method LeaveRequest        setReportReceived()  Sets the current record's "report_Received" value
 * @method LeaveRequest        setEmployee()        Sets the current record's "Employee" value
 * @method LeaveRequest        setLeaveType()       Sets the current record's "LeaveType" value
 * @method LeaveRequest        setWorkingHourDay()  Sets the current record's "WorkingHourDay" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveRequest extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leave_request');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Accepted',
              1 => 'Denied',
              2 => 'Pending',
              3 => 'Cancelled',
             ),
             'default' => 'Pending',
             'notnull' => true,
             ));
        $this->hasColumn('start_Date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end_Date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('day_Count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('report_Comment', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
        $this->hasColumn('report_Date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('report_Received', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LeaveType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('WorkingHourDay', array(
             'local' => 'id',
             'foreign' => 'leave_id'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}