<?php

/**
 * BaseWorkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $title
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $sfGuardGroupWorkType
 * @property Doctrine_Collection $WorkTypes
 * 
 * @method string              getCode()                 Returns the current record's "code" value
 * @method string              getTitle()                Returns the current record's "title" value
 * @method Doctrine_Collection getGroups()               Returns the current record's "Groups" collection
 * @method Doctrine_Collection getSfGuardGroupWorkType() Returns the current record's "sfGuardGroupWorkType" collection
 * @method Doctrine_Collection getWorkTypes()            Returns the current record's "WorkTypes" collection
 * @method WorkType            setCode()                 Sets the current record's "code" value
 * @method WorkType            setTitle()                Sets the current record's "title" value
 * @method WorkType            setGroups()               Sets the current record's "Groups" collection
 * @method WorkType            setSfGuardGroupWorkType() Sets the current record's "sfGuardGroupWorkType" collection
 * @method WorkType            setWorkTypes()            Sets the current record's "WorkTypes" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkType extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('work_type');
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('title', 'string', 250, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 250,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardGroupWorkType',
             'local' => 'worktype_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroupWorkType', array(
             'local' => 'id',
             'foreign' => 'worktype_id'));

        $this->hasMany('WorkingHour as WorkTypes', array(
             'local' => 'id',
             'foreign' => 'worktype_id'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}