<?php

/**
 * BaseLeaveRequestLimit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $employee_id
 * @property integer $type_id
 * @property integer $leaveLimit
 * @property sfGuardUser $Employee
 * @property LeaveType $LeaveType
 * 
 * @method integer           getEmployeeId()  Returns the current record's "employee_id" value
 * @method integer           getTypeId()      Returns the current record's "type_id" value
 * @method integer           getLeaveLimit()  Returns the current record's "leaveLimit" value
 * @method sfGuardUser       getEmployee()    Returns the current record's "Employee" value
 * @method LeaveType         getLeaveType()   Returns the current record's "LeaveType" value
 * @method LeaveRequestLimit setEmployeeId()  Sets the current record's "employee_id" value
 * @method LeaveRequestLimit setTypeId()      Sets the current record's "type_id" value
 * @method LeaveRequestLimit setLeaveLimit()  Sets the current record's "leaveLimit" value
 * @method LeaveRequestLimit setEmployee()    Sets the current record's "Employee" value
 * @method LeaveRequestLimit setLeaveType()   Sets the current record's "LeaveType" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveRequestLimit extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leave_request_limit');
        $this->hasColumn('employee_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('leaveLimit', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'employee_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LeaveType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}