<?php

/**
 * BaseWorkingHourWork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $day_id
 * @property integer $type_id
 * @property time $start
 * @property time $end
 * @property string $comment
 * @property WorkingHourDay $Day
 * @property WorkingHourWorkType $WorkType
 * 
 * @method integer             getDayId()    Returns the current record's "day_id" value
 * @method integer             getTypeId()   Returns the current record's "type_id" value
 * @method time                getStart()    Returns the current record's "start" value
 * @method time                getEnd()      Returns the current record's "end" value
 * @method string              getComment()  Returns the current record's "comment" value
 * @method WorkingHourDay      getDay()      Returns the current record's "Day" value
 * @method WorkingHourWorkType getWorkType() Returns the current record's "WorkType" value
 * @method WorkingHourWork     setDayId()    Sets the current record's "day_id" value
 * @method WorkingHourWork     setTypeId()   Sets the current record's "type_id" value
 * @method WorkingHourWork     setStart()    Sets the current record's "start" value
 * @method WorkingHourWork     setEnd()      Sets the current record's "end" value
 * @method WorkingHourWork     setComment()  Sets the current record's "comment" value
 * @method WorkingHourWork     setDay()      Sets the current record's "Day" value
 * @method WorkingHourWork     setWorkType() Sets the current record's "WorkType" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourWork extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_work');
        $this->hasColumn('day_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WorkingHourDay as Day', array(
             'local' => 'day_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('WorkingHourWorkType as WorkType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}