<?php

/**
 * BaseWorkingHourWorkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $WorkingHourWork
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getWorkingHourWork() Returns the current record's "WorkingHourWork" collection
 * @method WorkingHourWorkType setName()            Sets the current record's "name" value
 * @method WorkingHourWorkType setWorkingHourWork() Sets the current record's "WorkingHourWork" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourWorkType extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_work_type');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WorkingHourWork', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}