<?php

/**
 * BaseWorkingHourParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $param
 * @property string $value
 * @property string $description
 * 
 * @method string               getParam()       Returns the current record's "param" value
 * @method string               getValue()       Returns the current record's "value" value
 * @method string               getDescription() Returns the current record's "description" value
 * @method WorkingHourParameter setParam()       Sets the current record's "param" value
 * @method WorkingHourParameter setValue()       Sets the current record's "value" value
 * @method WorkingHourParameter setDescription() Sets the current record's "description" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourParameter extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_parameter');
        $this->hasColumn('param', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('value', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('orderBy', 'param ASC');
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}