<?php

/**
 * BaseLeaveRequestLimit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $type_id
 * @property integer $leaveLimit
 * @property sfGuardUser $Employee
 * @property LeaveRequestType $LeaveType
 * 
 * @method integer           getUserId()     Returns the current record's "user_id" value
 * @method integer           getTypeId()     Returns the current record's "type_id" value
 * @method integer           getLeaveLimit() Returns the current record's "leaveLimit" value
 * @method sfGuardUser       getEmployee()   Returns the current record's "Employee" value
 * @method LeaveRequestType  getLeaveType()  Returns the current record's "LeaveType" value
 * @method LeaveRequestLimit setUserId()     Sets the current record's "user_id" value
 * @method LeaveRequestLimit setTypeId()     Sets the current record's "type_id" value
 * @method LeaveRequestLimit setLeaveLimit() Sets the current record's "leaveLimit" value
 * @method LeaveRequestLimit setEmployee()   Sets the current record's "Employee" value
 * @method LeaveRequestLimit setLeaveType()  Sets the current record's "LeaveType" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLeaveRequestLimit extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leave_request_limit');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('leaveLimit', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Employee', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('LeaveRequestType as LeaveType', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}