<?php

/**
 * BaseWorkingHourRecord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $day_id
 * @property enum $recordType
 * @property time $start_Time
 * @property time $end_Time
 * @property integer $project_id
 * @property integer $work_Type_id
 * @property string $comment
 * @property WorkingHourDay $Day
 * @property Project $Project
 * @property WorkingHourWorkType $WorkType
 * 
 * @method integer             getDayId()        Returns the current record's "day_id" value
 * @method enum                getRecordType()   Returns the current record's "recordType" value
 * @method time                getStartTime()    Returns the current record's "start_Time" value
 * @method time                getEndTime()      Returns the current record's "end_Time" value
 * @method integer             getProjectId()    Returns the current record's "project_id" value
 * @method integer             getWorkTypeId()   Returns the current record's "work_Type_id" value
 * @method string              getComment()      Returns the current record's "comment" value
 * @method WorkingHourDay      getDay()          Returns the current record's "Day" value
 * @method Project             getProject()      Returns the current record's "Project" value
 * @method WorkingHourWorkType getWorkType()     Returns the current record's "WorkType" value
 * @method WorkingHourRecord   setDayId()        Sets the current record's "day_id" value
 * @method WorkingHourRecord   setRecordType()   Sets the current record's "recordType" value
 * @method WorkingHourRecord   setStartTime()    Sets the current record's "start_Time" value
 * @method WorkingHourRecord   setEndTime()      Sets the current record's "end_Time" value
 * @method WorkingHourRecord   setProjectId()    Sets the current record's "project_id" value
 * @method WorkingHourRecord   setWorkTypeId()   Sets the current record's "work_Type_id" value
 * @method WorkingHourRecord   setComment()      Sets the current record's "comment" value
 * @method WorkingHourRecord   setDay()          Sets the current record's "Day" value
 * @method WorkingHourRecord   setProject()      Sets the current record's "Project" value
 * @method WorkingHourRecord   setWorkType()     Sets the current record's "WorkType" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourRecord extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_record');
        $this->hasColumn('day_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('recordType', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Work',
              1 => 'Entrance',
              2 => 'Exit',
             ),
             'default' => 'Work',
             'notnull' => true,
             ));
        $this->hasColumn('start_Time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('end_Time', 'time', null, array(
             'type' => 'time',
             'notnull' => false,
             ));
        $this->hasColumn('project_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('work_Type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('comment', 'string', 50, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 50,
             ));

        $this->option('orderBy', 'day_id, start_Time, end_Time ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WorkingHourDay as Day', array(
             'local' => 'day_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Project', array(
             'local' => 'project_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('WorkingHourWorkType as WorkType', array(
             'local' => 'work_Type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}