<?php

/**
 * BaseWorkingHourWorkType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property Doctrine_Collection $Employees
 * @property Doctrine_Collection $Departments
 * @property Doctrine_Collection $Department
 * @property Doctrine_Collection $WorkingHourWork
 * 
 * @method string              getCode()                     Returns the current record's "code" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method Doctrine_Collection getEmployees()                Returns the current record's "Employees" collection
 * @method Doctrine_Collection getDepartments()              Returns the current record's "Departments" collection
 * @method Doctrine_Collection getDepartment()               Returns the current record's "Department" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeUser()  Returns the current record's "WorkingHourWorkTypeUser" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeGroup() Returns the current record's "WorkingHourWorkTypeGroup" collection
 * @method Doctrine_Collection getWorkingHourWork()          Returns the current record's "WorkingHourWork" collection
 * @method WorkingHourWorkType setCode()                     Sets the current record's "code" value
 * @method WorkingHourWorkType setName()                     Sets the current record's "name" value
 * @method WorkingHourWorkType setEmployees()                Sets the current record's "Employees" collection
 * @method WorkingHourWorkType setDepartments()              Sets the current record's "Departments" collection
 * @method WorkingHourWorkType setDepartment()               Sets the current record's "Department" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeUser()  Sets the current record's "WorkingHourWorkTypeUser" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeGroup() Sets the current record's "WorkingHourWorkTypeGroup" collection
 * @method WorkingHourWorkType setWorkingHourWork()          Sets the current record's "WorkingHourWork" collectionTypeUser
 * @property Doctrine_Collection $WorkingHourWork
 * 
 * @method string              getCode()                     Returns the current record's "code" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method Doctrine_Collection getEmployees()                Returns the current record's "Employees" collection
 * @method Doctrine_Collection getDepartments()              Returns the current record's "Departments" collection
 * @method Doctrine_Collection getDepartment()               Returns the current record's "Department" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeUser()  Returns the current record's "WorkingHourWorkTypeUser" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeGroup() Returns the current record's "WorkingHourWorkTypeGroup" collection
 * @method Doctrine_Collection getWorkingHourWork()          Returns the current record's "WorkingHourWork" collection
 * @method WorkingHourWorkType setCode()                     Sets the current record's "code" value
 * @method WorkingHourWorkType setName()                     Sets the current record's "name" value
 * @method WorkingHourWorkType setEmployees()                Sets the current record's "Employees" collection
 * @method WorkingHourWorkType setDepartments()              Sets the current record's "Departments" collection
 * @method WorkingHourWorkType setDepartment()               Sets the current record's "Department" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeUser()  Sets the current record's "WorkingHourWorkTypeUser" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeGroup() Sets the current record's "WorkingHourWorkTypeGroup" collection
 * @method WorkingHourWorkType setWorkingHourWork()          Sets the current record's "WorkingHourWork" collectionTypeGroup
 * @property Doctrine_Collection $WorkingHourWork
 * 
 * @method string              getCode()                     Returns the current record's "code" value
 * @method string              getName()                     Returns the current record's "name" value
 * @method Doctrine_Collection getEmployees()                Returns the current record's "Employees" collection
 * @method Doctrine_Collection getDepartments()              Returns the current record's "Departments" collection
 * @method Doctrine_Collection getDepartment()               Returns the current record's "Department" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeUser()  Returns the current record's "WorkingHourWorkTypeUser" collection
 * @method Doctrine_Collection getWorkingHourWorkTypeGroup() Returns the current record's "WorkingHourWorkTypeGroup" collection
 * @method Doctrine_Collection getWorkingHourWork()          Returns the current record's "WorkingHourWork" collection
 * @method WorkingHourWorkType setCode()                     Sets the current record's "code" value
 * @method WorkingHourWorkType setName()                     Sets the current record's "name" value
 * @method WorkingHourWorkType setEmployees()                Sets the current record's "Employees" collection
 * @method WorkingHourWorkType setDepartments()              Sets the current record's "Departments" collection
 * @method WorkingHourWorkType setDepartment()               Sets the current record's "Department" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeUser()  Sets the current record's "WorkingHourWorkTypeUser" collection
 * @method WorkingHourWorkType setWorkingHourWorkTypeGroup() Sets the current record's "WorkingHourWorkTypeGroup" collection
 * @method WorkingHourWorkType setWorkingHourWork()          Sets the current record's "WorkingHourWork" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourWorkType extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_work_type');
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 5,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));

        $this->option('orderBy', 'code ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Employees', array(
             'refClass' => 'WorkingHourWorkTypeUser',
             'local' => 'worktype_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardGroup as Departments', array(
             'refClass' => 'WorkingHourWorkTypeGroup',
             'local' => 'worktype_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroup as Department', array(
             'local' => 'id',
             'foreign' => 'default_Worktype_id'));

        $this->hasMany('WorkingHourWorkTypeUser', array(
             'local' => 'id',
             'foreign' => 'worktype_id'));

        $this->hasMany('WorkingHourWorkTypeGroup', array(
             'local' => 'id',
             'foreign' => 'worktype_id'));

        $this->hasMany('WorkingHourWork', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}