<?php

/**
 * BaseWorkingHourWorkTypeGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $worktype_id
 * @property integer $group_id
 * @property WorkingHourWorkType $WorkingHourWorkType
 * @property sfGuardGroup $Department
 * 
 * @method integer                  getWorktypeId()          Returns the current record's "worktype_id" value
 * @method integer                  getGroupId()             Returns the current record's "group_id" value
 * @method WorkingHourWorkType      getWorkingHourWorkType() Returns the current record's "WorkingHourWorkType" value
 * @method sfGuardGroup             getDepartment()          Returns the current record's "Department" value
 * @method WorkingHourWorkTypeGroup setWorktypeId()          Sets the current record's "worktype_id" value
 * @method WorkingHourWorkTypeGroup setGroupId()             Sets the current record's "group_id" value
 * @method WorkingHourWorkTypeGroup setWorkingHourWorkType() Sets the current record's "WorkingHourWorkType" value
 * @method WorkingHourWorkTypeGroup setDepartment()          Sets the current record's "Department" value
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWorkingHourWorkTypeGroup extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('working_hour_work_type_group');
        $this->hasColumn('worktype_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WorkingHourWorkType', array(
             'local' => 'worktype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Department', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}