<?php

/**
 * BaseCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $symbol
 * @property boolean $isDefault
 * @property boolean $isActive
 * @property Doctrine_Collection $CostForms
 * @property Doctrine_Collection $CostFormItems
 * 
 * @method string              getCode()          Returns the current record's "code" value
 * @method string              getSymbol()        Returns the current record's "symbol" value
 * @method boolean             getIsDefault()     Returns the current record's "isDefault" value
 * @method boolean             getIsActive()      Returns the current record's "isActive" value
 * @method Doctrine_Collection getCostForms()     Returns the current record's "CostForms" collection
 * @method Doctrine_Collection getCostFormItems() Returns the current record's "CostFormItems" collection
 * @method Currency            setCode()          Sets the current record's "code" value
 * @method Currency            setSymbol()        Sets the current record's "symbol" value
 * @method Currency            setIsDefault()     Sets the current record's "isDefault" value
 * @method Currency            setIsActive()      Sets the current record's "isActive" value
 * @method Currency            setCostForms()     Sets the current record's "CostForms" collection
 * @method Currency            setCostFormItems() Sets the current record's "CostFormItems" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrency extends MyDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency');
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 3,
             ));
        $this->hasColumn('symbol', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('isDefault', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('isActive', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             'notnull' => true,
             ));

        $this->option('orderBy', 'code ASC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CostForm as CostForms', array(
             'local' => 'id',
             'foreign' => 'currency_id'));

        $this->hasMany('CostFormItem as CostFormItems', array(
             'local' => 'id',
             'foreign' => 'currency_id'));

        $auditable0 = new Doctrine_Template_Auditable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($auditable0);
        $this->actAs($softdelete0);
        $this->actAs($versionable0);
    }
}