all: #is valid for all applications

   menus: #defines iOMenuPlugin menu

      topmenu: #defines top menu - tabs
      
         name: Top Menu
         
         attributes:
         
            id: LayoutTopMenu
            class: "nav nav-tabs"
               #Using bootstrap 2x
          
         children:
         
            0: #default homepage
            
               label: Home
               route: @homepage
               requires_auth: true
               is_first: true
               
            99: #TODO: should be seperated plugins itself - Issue #26
            
               label: Settings
               route: @administration
               requires_auth: true
               
               
      leftmenu_administration: #initializes left menu in Admin pages
      
         name: Left Menu
         
         attributes: { class: "nav nav-list" }
            #Using bootstrap 2x
