all:
  menus:
    topmenu:
      name: Top Menu
      attributes: {id: LayoutTopMenu, class: "nav nav-tabs" }
      children:
        0:
          label: Home
          route: @homepage
          requires_auth: true
          is_first: true
        99:
          label: Administration
          route: @administration
          requires_auth: true
          credentials: [["Currency Management", "Customer Management", "Employee Management", "Project Management", "VAT Management"]]
    
    leftmenu_administration:
      name: Left Menu
      attributes: { class: "nav nav-list" }
      children:
        00:
          label: Program Settings
          attributes: { class: "nav-header" }
          requires_auth: true
