all:
    #iOMenuPlugin
    menus:    
        topmenu:
            name: Top Menu
            attributes:
                id: layout_top_menu
                class: "nav"
            children:
                0_welcome:
                    label: Welcome
                    route: @homepage
                99_settings: 
                    label: Settings
                    route: "#"
                    attributes:
                        id: topmenu_settings
                        class: "dropdown"
