prod:
    logger:
        class:   sfNoLogger
        param:
            level:   err
            loggers: ~

all:
    routing:
        class: sfPatternRouting
        param:
            generate_shortest_url:            true
            extra_parameters_as_query_string: true
            context:
                host: fmcserver.dyndns.org
    
    view_cache_manager:
        class: sfViewCacheManager
        param:
            cache_key_use_vary_headers: true
            cache_key_use_host_name:    true
    
    mailer:
        class: sfMailer
        param:
            logging:           %SF_LOGGING_ENABLED%
            charset:           %SF_CHARSET%
            delivery_strategy: realtime
            transport:
                class: Swift_SmtpTransport
                param:
                    host:       mail.fmconsulting.info
                    port:       587
                    encryption: ~
                    username:   datamanagement@fmconsulting.info
                    password:   fmcon2793DM
