# Main Pages

homepage:
    url: /
    param:
        module: homepage
        action: index

administration:
    url: /home/administration
    param:
        module: homepage
        action: administration

# sfDoctrineGuard - Login/Logout Operations

sf_guard_signin:
    url: /login
    param:
        module: sfGuardAuth
        action: signin

sf_guard_signout:
    url:  /logout
    param:
        module: sfGuardAuth
        action: signout
