# sfDoctrineGuard - Login/Logout Operations

sf_guard_signin:
    url: /login
    param:
        module: sfGuardAuth
        action: signin

sf_guard_signout:
    url:  /logout
    param:
        module: sfGuardAuth
        action: signout
