default:
  http_metas:
    content-type: text/html

  metas:
    title:        FMC Data Management
    language:     en
  
  stylesheets:
    - jqueryui-flick/jquery-ui.css
    - /bootstrap/css/bootstrap.min.css
    - frontend/tablesorter-extra.css
    - timepicker/timepicker.css
    
    #- frontend/global.css
    #- frontend/layout.css
    #- frontend/forms.css
    #- frontend/override.css
  
  javascripts:
    - jquery.js
    - jquery-ui.js
    - jquery-tablesorter.js
    - jquery.tablesorter.pager.js
    - jquery.timepicker.js
    - /bootstrap/js/bootstrap.min.js
    - frontend.js
  
  has_layout:     true
  layout:         layout
