default:
  http_metas:
    content-type: text/html

  metas:
    title:        FMC Data Management
    language:     en
  
  stylesheets:
    - jqueryui-flick/jquery-ui.css
    - bootstrap.css
    - frontend/global.css
    - frontend/layout.css
    - frontend/forms.css
  
  javascripts: 
    - jquery.js
    - jquery-tablesorter.js
    - jquery-ui.js
    - frontend.js
  
  has_layout:     true
  layout:         layout
