default:
    http_metas:
        content-type: text/html
    
    metas:
        title:        FMC Data Management
        language:     en
    
    stylesheets:
        - /addons/jquery-ui-1.8.23/css/flick/jquery-ui-1.8.23.custom.css
        #- /addons/bootstrap-2.1.1/css/bootstrap.min.css
        - /addons/tablesorter/css/tablesorter-extra.css
        - /addons/timepicker/css/timepicker.css
        
        - /plugins/bootstrap/css/bootstrap.min.css
        - frontend-extra.css
        - frontend-forms.css
        
        #- frontend/layout.css
        #- frontend/fixes.css
        #- frontend/forms.css
        #- frontend/override/bootstrap.css
        #- frontend/override/jqueryui.css
        #- frontend/override/timepicker.css
        #- frontend/override/tablesorter.css
        
        
    javascripts:
        - /addons/jquery-ui-1.8.23/js/jquery-1.8.0.min.js
        - /addons/jquery-ui-1.8.23/js/jquery-ui-1.8.23.custom.min.js
        - /addons/tablesorter/js/jquery-tablesorter.js
        - /addons/tablesorter/js/jquery.tablesorter.pager.js
        - /addons/timepicker/js/jquery.timepicker.js
        #- /addons/bootstrap-2.1.1/js/bootstrap.min.js
        
        
        - /plugins/bootstrap/js/bootstrap.min.js
        
        - frontend.js
        
    has_layout:     true
    layout:         layout
