<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cfdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function getDepartmentname()
  {
    $department = Doctrine::getTable('sfGuardGroup')
      ->createQuery('wh')
      ->addWhere('wh.id = ?', $this->group_id)
      ->fetchOne();
    
    return $department;
  }
}
