<?php

/**
 * PluginWorkingHourRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourRecordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourRecord');
    }
}