<?php

/**
 * PluginLeaveRequestTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveRequestTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveRequestTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveRequestType');
    }
}