<?php

/**
 * PluginsfGuardUserWorktypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserWorktypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserWorktypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserWorktype');
    }
}