<?php

/**
 * PluginWorkingHourLeaveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourLeaveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourLeaveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourLeave');
    }
}