<?php

/**
 * PluginsfGuardGroupWorktypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardGroupWorktypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardGroupWorktypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardGroupWorktype');
    }
}