<?php

/**
 * PluginLeaveRequestLimitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginLeaveRequestLimitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginLeaveRequestLimitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginLeaveRequestLimit');
    }
}