<?php

/**
 * PluginWorkingHourEntranceExitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourEntranceExitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourEntranceExitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourEntranceExit');
    }
}