<?php

/**
 * PluginWorkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkType');
    }
}