<?php

/**
 * PluginWorkingHourParameterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourParameterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourParameterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourParameter');
    }
}