<?php

/**
 * PluginWorkingHourWorkTypeUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourWorkTypeUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourWorkTypeUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourWorkTypeUser');
    }
}