<?php

/**
 * PluginWorkingHourWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourWorkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourWork');
    }
}