<?php

/**
 * PluginWorkingHourQuotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourQuotaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourQuotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourQuota');
    }
}