<?php

/**
 * PluginCustomWorkingHourTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCustomWorkingHourTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCustomWorkingHourTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCustomWorkingHour');
    }
}