<?php

/**
 * PluginWorkingHourWorkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourWorkTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourWorkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourWorkType');
    }
    
    public function __construct($name, Doctrine_Connection $conn, $initDefinition = false)
    {
        parent::__construct($name, $conn, $initDefinition);
        $this->_options['orderBy'] = 'code ASC';
    }
    
}
