<?php

/**
 * PluginWorkingHourWorkTypeGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourWorkTypeGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourWorkTypeGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourWorkTypeGroup');
    }
}