<?php

/**
 * PluginsfGuardGroupWorkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardGroupWorkTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardGroupWorkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardGroupWorkType');
    }
}