<?php

/**
 * PluginWorkingHourDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWorkingHourDayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWorkingHourDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWorkingHourDay');
    }
    
    /* User defined functions below */
    
    
    public function getEntranceForDate ($user_id, $date) {
      
      $result = Doctrine_Query::create()
        ->from ('WorkingHourDay')
        ->addWhere ('user_id = ?', $user_id)
        ->addWhere ('date = ?', $date)
        ->fetchOne();
      
      return $result;
    }
    
}
