<?php

/**
 * BaseCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $created_by
 * @property integer $updated_by
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Updater
 * @property Doctrine_Collection $Projects
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getCreatedBy()  Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()  Returns the current record's "updated_by" value
 * @method sfGuardUser         getCreator()    Returns the current record's "Creator" value
 * @method sfGuardUser         getUpdater()    Returns the current record's "Updater" value
 * @method Doctrine_Collection getProjects()   Returns the current record's "Projects" collection
 * @method Customer            setName()       Sets the current record's "name" value
 * @method Customer            setCreatedBy()  Sets the current record's "created_by" value
 * @method Customer            setUpdatedBy()  Sets the current record's "updated_by" value
 * @method Customer            setCreator()    Sets the current record's "Creator" value
 * @method Customer            setUpdater()    Sets the current record's "Updater" value
 * @method Customer            setProjects()   Sets the current record's "Projects" collection
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('created_by', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('updated_by', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Updater', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Project as Projects', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $versionable0 = new Doctrine_Template_Versionable();
        $this->actAs($softdelete0);
        $this->actAs($timestampable0);
        $this->actAs($versionable0);
    }
}