<?php

/**
 * CostFormItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostFormItemTable extends PluginCostFormItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostFormItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CostFormItem');
    }
}