<?php

/**
 * CostFormInvoicingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostFormInvoicingTable extends PluginCostFormInvoicingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostFormInvoicingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CostFormInvoicing');
    }
}