<?php

/**
 * CostFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostFormTable extends PluginCostFormTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CostForm');
    }
}