<?php

/**
 * CostFormInvoicingItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CostFormInvoicingItemTable extends PluginCostFormInvoicingItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CostFormInvoicingItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CostFormInvoicingItem');
    }
}