<?php

/**
 * CustomWorkingHourTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomWorkingHourTable extends PluginCustomWorkingHourTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomWorkingHourTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomWorkingHour');
    }
}