<?php

/**
 * LeaveRequestTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveRequestTypeTable extends PluginLeaveRequestTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveRequestTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveRequestType');
    }
}