<?php

/**
 * LeaveRequestLimitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveRequestLimitTable extends PluginLeaveRequestLimitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveRequestLimitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveRequestLimit');
    }
}