<?php

/**
 * LeaveRequestEmployeeLimitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LeaveRequestEmployeeLimitTable extends PluginLeaveRequestEmployeeLimitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LeaveRequestEmployeeLimitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LeaveRequestEmployeeLimit');
    }
}