<?php

/**
 * sfGuardGroupWorkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupWorkTypeTable extends PluginsfGuardGroupWorkTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupWorkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroupWorkType');
    }
}