<?php

/**
 * sfGuardUserWorktypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserWorktypeTable extends PluginsfGuardUserWorktypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserWorktypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserWorktype');
    }
}