<?php

/**
 * sfGuardGroupWorktypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupWorktypeTable extends PluginsfGuardGroupWorktypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardGroupWorktypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardGroupWorktype');
    }
}