<?php

/**
 * WorkingHourEntranceExitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourEntranceExitTable extends PluginWorkingHourEntranceExitTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourEntranceExitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourEntranceExit');
    }
}