<?php

/**
 * WorkingHourWorkTypeUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourWorkTypeUserTable extends PluginWorkingHourWorkTypeUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourWorkTypeUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourWorkTypeUser');
    }
}