<?php

/**
 * WorkingHourTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourTable extends PluginWorkingHourTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHour');
    }
}