<?php

/**
 * WorkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkTypeTable extends PluginWorkTypeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkType');
    }
}