<?php

/**
 * WorkingHourWorkTypeGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourWorkTypeGroupTable extends PluginWorkingHourWorkTypeGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourWorkTypeGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourWorkTypeGroup');
    }
}