<?php

/**
 * WorkingHourEntranceExit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    fmc
 * @subpackage model
 * @author     Yasin Aydin (yasin@yasinaydin.net)
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WorkingHourEntranceExit extends PluginWorkingHourEntranceExit
{
}
