<?php

/**
 * WorkingHourWorkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourWorkTable extends PluginWorkingHourWorkTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourWorkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourWork');
    }
}