<?php

/**
 * WorkingHourQuotaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourQuotaTable extends PluginWorkingHourQuotaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourQuotaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourQuota');
    }
}