<?php

/**
 * WorkingHourDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WorkingHourDayTable extends PluginWorkingHourDayTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object WorkingHourDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WorkingHourDay');
    }
}