<?php

/**
 * PluginVatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginVatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginVatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginVat');
    }
    
  public function getActive()
  {
    return $this->CreateQuery('v')
      ->where('v.isActive = ?', true)
      ->orderBy('v.rate ASC')
      ->execute();
  }
}
