<?php

/**
 * PluginCostFormInvoicingItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCostFormInvoicingItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCostFormInvoicingItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCostFormInvoicingItem');
    }
}