<?php

/**
 * PluginCostFormInvoicingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCostFormInvoicingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCostFormInvoicingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCostFormInvoicing');
    }
}