<?php

/**
 * PluginCostFormItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginCostFormItem extends BaseCostFormItem
{
  public function getWithoutVat()
  {
    if ( !$this->amount or $this->amount==0 )
    {
      return 0;
    }
    elseif ( $this->Vats->rate == 0)
    {
      return $this->amount;
    }
    else
    {
      return round( 100/(100+$this->Vats->rate)*$this->amount , 2);
    }
  }
}
